name: Generate DevCard

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

#  push: {branches: ["master", "main"]}
jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.1.0
        with:
          user_id: ${{ secrets.DEVCARD_ID }}
