name: Generate General

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */8 * * *"
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
      - master



jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:

      - name: 🦑 Medias
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: medias.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_order: anilist, music
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_music: yes
          plugin_music_playlist: ${{ secrets.PLAYLIST }}
          plugin_music_limit: 9
